spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${PORT:5433}/${DB_NAME:app-db}?currentSchema=${SCHEMA:auth_db}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME:postgres}
    password: ${PASSWORD:postgres}

    hikari:
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_schema: ${SCHEMA:auth_db}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


  liquibase:
    enabled: false
    change-log: classpath:/db.changelog/db.changelog.yaml


server:
  port: 8081
  servlet:
    context-path: /api/auth-service

jwt:
  secret: "CHANGE_TO_32+_CHAR_RANDOM_SECRET"
  access-exp: 900000    # 15 minutes
  refresh-exp: 604800000 # 7 days

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

